import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL!);

const games = [
  {
    slug: 'bonk-io',
    title_es: 'Bonk.io', title_en: 'Bonk.io',
    tagline_es: 'Física multijugador: empuja a todos fuera de la plataforma.',
    tagline_en: 'Multiplayer physics: push everyone off the platform.',
    description_es: 'Bonk.io es el juego de física multijugador más divertido del navegador. Crea una sala privada con código, invita a tus amigos y empujad a todos fuera de la plataforma usando física realista. Mapas personalizables, hasta 6 jugadores por sala, modo pesado/ligero. Perfecto para sesiones caóticas con amigos — cada partida es diferente.',
    description_en: 'Bonk.io is the most fun physics multiplayer browser game. Create a private room with code, invite friends and push everyone off the platform using realistic physics. Customizable maps, up to 6 players per room, heavy/light mode. Perfect for chaotic friend sessions.',
    instructions_es: 'WASD o flechas para mover. X para activar modo pesado (más difícil de empujar). Crea sala privada desde el menú.',
    instructions_en: 'WASD or arrows to move. X to activate heavy mode (harder to push). Create private room from the menu.',
    embed_url: 'https://bonk.io',
    thumb_url: '/thumbs/bonk-io.svg',
    min_players: 2, max_players: 6,
    category_slugs: ['cooperativos', 'multijugador', 'dos-jugadores'],
    featured: true,
  },
  {
    slug: 'drunken-wrestlers-2',
    title_es: 'Drunken Wrestlers 2', title_en: 'Drunken Wrestlers 2',
    tagline_es: 'Lucha con físicas ragdoll borracho para 2 jugadores.',
    tagline_en: '2-player drunken ragdoll physics wrestling.',
    description_es: 'Drunken Wrestlers 2 es un juego de lucha con físicas ragdoll completamente descontroladas. Tus luchadores se tambalean borrachos mientras intentas golpear al rival. La imprevisibilidad de los movimientos garantiza momentos hilarantes. Múltiples personajes y arenas.',
    description_en: 'Drunken Wrestlers 2 is a fighting game with completely out-of-control ragdoll physics. Your wrestlers stumble drunkenly while you try to hit the opponent. The unpredictability of movements guarantees hilarious moments.',
    instructions_es: 'Jugador 1: A/D mover, W saltar, S agacharse, Q/E golpear. Jugador 2: Flechas + numpad.',
    instructions_en: 'Player 1: A/D move, W jump, S crouch, Q/E punch. Player 2: Arrows + numpad.',
    embed_url: 'https://www.crazygames.com/embed/drunken-wrestlers-2',
    thumb_url: '/thumbs/drunken-wrestlers-2.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'wrestle-jump',
    title_es: 'Wrestle Jump', title_en: 'Wrestle Jump',
    tagline_es: 'Lucha saltando: gana 5 rondas y eres el campeón.',
    tagline_en: 'Jump wrestling: win 5 rounds and you are champion.',
    description_es: 'Wrestle Jump es un juego de lucha minimalista para 2 jugadores. Cada personaje solo salta — el que caiga de cabeza pierde la ronda. La física caótica hace imposible predecir el resultado. Solo 2 botones por jugador, aprendizaje instantáneo, diversión garantizada.',
    description_en: 'Wrestle Jump is a minimalist fighting game for 2 players. Each character only jumps — whoever falls on their head loses the round. Chaotic physics make results impossible to predict. Only 2 buttons per player, instant learning, guaranteed fun.',
    instructions_es: 'Jugador 1: A/D para saltar-izq/der. Jugador 2: Teclas flecha izq/der.',
    instructions_en: 'Player 1: A/D to jump-left/right. Player 2: Left/right arrow keys.',
    embed_url: 'https://www.crazygames.com/embed/wrestle-jump',
    thumb_url: '/thumbs/wrestle-jump.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'rocket-bot-royale',
    title_es: 'Rocket Bot Royale', title_en: 'Rocket Bot Royale',
    tagline_es: 'Tanques con física y cohetes en un battle royale multijugador.',
    tagline_en: 'Physics tanks and rockets in a multiplayer battle royale.',
    description_es: 'Rocket Bot Royale es un battle royale de tanques con física realista de proyectiles. El agua sube progresivamente y elimina a los que caen. Dispara cohetes con trayectorias de parábola, defiéndete con el escudo y construye plataformas para sobrevivir. Uno de los mejores juegos de física multijugador del navegador.',
    description_en: 'Rocket Bot Royale is a tank battle royale with realistic projectile physics. Water rises and eliminates those who fall. Fire rockets with parabolic trajectories, defend with shield and build platforms to survive. One of the best physics multiplayer browser games.',
    instructions_es: 'Flechas mover · Ratón apuntar y disparar · W construir plataforma · S colocar mina.',
    instructions_en: 'Arrows move · Mouse aim and shoot · W build platform · S place mine.',
    embed_url: 'https://www.crazygames.com/embed/rocket-bot-royale',
    thumb_url: '/thumbs/rocket-bot-royale.svg',
    min_players: 2, max_players: 30,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'curve-fever-pro',
    title_es: 'Curve Fever Pro', title_en: 'Curve Fever Pro',
    tagline_es: 'Serpientes multijugador online: no cortes el rastro de nadie.',
    tagline_en: 'Online multiplayer curves: don\'t cross anyone\'s trail.',
    description_es: 'Curve Fever Pro es el evolución del clásico juego de serpientes. Hasta 6 jugadores online dejan un rastro en el mapa — si cruzas cualquier rastro (incluido el tuyo) mueres. Power-ups que doblan el rastro, abren huecos, te hacen girar... Estrategia y reflejos en tiempo real. Crea sala privada para jugar con amigos.',
    description_en: 'Curve Fever Pro is the evolution of the classic snake game. Up to 6 online players leave a trail on the map — cross any trail (including your own) and you die. Power-ups that widen the trail, create gaps, make you turn... Strategy and real-time reflexes.',
    instructions_es: 'Flechas izq/der para girar. Barra espaciadora para usar power-up. Crea sala desde el menú.',
    instructions_en: 'Left/right arrows to turn. Space bar to use power-up. Create room from menu.',
    embed_url: 'https://www.crazygames.com/embed/curve-fever-pro',
    thumb_url: '/thumbs/curve-fever-pro.svg',
    min_players: 2, max_players: 6,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'wings-io',
    title_es: 'Wings.io', title_en: 'Wings.io',
    tagline_es: 'Combate aéreo multijugador online: el avión más grande gana.',
    tagline_en: 'Online multiplayer aerial combat: the biggest plane wins.',
    description_es: 'Wings.io es un juego de combate aéreo multijugador en tiempo real. Pilota tu avión, recoge potenciadores para crecer y elimina a los aviones más pequeños. Tiene modo equipo donde puedes coordinarte con otros jugadores. Controles simples, acción frenética, partidas rápidas.',
    description_en: 'Wings.io is a real-time multiplayer aerial combat game. Pilot your plane, collect power-ups to grow and eliminate smaller planes. Has team mode for coordination. Simple controls, frantic action, quick matches.',
    instructions_es: 'Ratón o WASD para dirigir el avión. Click o espacio para disparar.',
    instructions_en: 'Mouse or WASD to steer the plane. Click or space to shoot.',
    embed_url: 'https://wings.io',
    thumb_url: '/thumbs/wings-io.svg',
    min_players: 2, max_players: 100,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'sketchful-io',
    title_es: 'Sketchful.io', title_en: 'Sketchful.io',
    tagline_es: 'Dibuja y adivina con amigos en sala privada.',
    tagline_en: 'Draw and guess with friends in a private room.',
    description_es: 'Sketchful.io es un juego de dibujo y adivinanza multijugador. Crea sala privada, elige palabras en español, y turnos para dibujar mientras los demás adivinan. Similar a Pictionary pero online y gratis. Categorías personalizables, palabras en español disponibles, hasta 12 jugadores por sala.',
    description_en: 'Sketchful.io is a multiplayer draw-and-guess game. Create a private room, choose words, take turns drawing while others guess. Similar to Pictionary but online and free. Customizable categories, up to 12 players per room.',
    instructions_es: 'Cuando te toca: dibuja la palabra con las herramientas. Cuando adivinas: escribe en el chat.',
    instructions_en: 'When it\'s your turn: draw the word with the tools. When guessing: type in chat.',
    embed_url: 'https://sketchful.io',
    thumb_url: '/thumbs/sketchful-io.svg',
    min_players: 2, max_players: 12,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'powerline-io',
    title_es: 'Powerline.io', title_en: 'Powerline.io',
    tagline_es: 'Serpiente eléctrica multijugador: crece y elimina a los rivales.',
    tagline_en: 'Electric snake multiplayer: grow and eliminate rivals.',
    description_es: 'Powerline.io moderniza el clásico Snake con gráficos de neón y multijugador online masivo. Tu serpiente eléctrica crece al pasar por potenciadores. Elimina rivales haciéndolos chocar con tu cuerpo. Aspecto visual espectacular con efectos de luz de neón sobre fondo oscuro.',
    description_en: 'Powerline.io modernizes classic Snake with neon graphics and massive online multiplayer. Your electric snake grows by passing through power-ups. Eliminate rivals by making them crash into your body.',
    instructions_es: 'Mueve el ratón para dirigir la serpiente. Haz click para acelerar.',
    instructions_en: 'Move the mouse to steer the snake. Click to boost.',
    embed_url: 'https://powerline.io',
    thumb_url: '/thumbs/powerline-io.svg',
    min_players: 2, max_players: 200,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'territorial-io',
    title_es: 'Territorial.io', title_en: 'Territorial.io',
    tagline_es: 'Conquista el mapa en este estratégico multijugador online.',
    tagline_en: 'Conquer the map in this strategic online multiplayer.',
    description_es: 'Territorial.io es un juego de conquista de territorio con mecánicas estratégicas. Expande tu nación atacando territorios vecinos, forma alianzas con otros jugadores y domina el mapa. Las partidas tienen cientos de jugadores simultáneos. Requiere pensar antes de atacar.',
    description_en: 'Territorial.io is a territory conquest game with strategic mechanics. Expand your nation by attacking neighboring territories, form alliances with other players and dominate the map. Matches have hundreds of simultaneous players.',
    instructions_es: 'Click en territorio adyacente para atacar. La barra de carga determina la fuerza del ataque.',
    instructions_en: 'Click on adjacent territory to attack. The charge bar determines attack strength.',
    embed_url: 'https://territorial.io',
    thumb_url: '/thumbs/territorial-io.svg',
    min_players: 2, max_players: 500,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'bowman',
    title_es: 'Bowman', title_en: 'Bowman',
    tagline_es: 'Duelo de arqueros para 2: apunta, ajusta el viento y dispara.',
    tagline_en: '2-player archer duel: aim, adjust for wind and shoot.',
    description_es: 'Bowman es el clásico duelo de arqueros en navegador. Apunta ajustando el ángulo y la fuerza del disparo, ten en cuenta el viento y elimina al arquero rival. Modo 2 jugadores en el mismo dispositivo o contra la IA. Un clásico que nunca falla para una partida rápida.',
    description_en: 'Bowman is the classic browser archer duel. Aim by adjusting angle and shot power, account for wind and eliminate the rival archer. 2-player mode on the same device or vs AI.',
    instructions_es: 'Arrastra el ratón para ajustar dirección y fuerza. Suelta para disparar. Alterna turnos.',
    instructions_en: 'Drag mouse to adjust direction and power. Release to shoot. Alternate turns.',
    embed_url: 'https://www.crazygames.com/embed/bowman',
    thumb_url: '/thumbs/bowman.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'ludo-online',
    title_es: 'Ludo Online (Parchís)', title_en: 'Ludo Online',
    tagline_es: 'Parchís clásico multijugador online para 2 a 4 jugadores.',
    tagline_en: 'Classic Ludo multiplayer online for 2 to 4 players.',
    description_es: 'La versión online del parchís clásico. Juega con amigos o con desconocidos en partidas de 2 a 4 jugadores. Lanza los dados, mueve tus fichas y lleva todas al hogar antes que los demás. El juego de mesa más popular de España ahora en el navegador.',
    description_en: 'The online version of classic Ludo. Play with friends or strangers in 2 to 4 player matches. Roll the dice, move your pieces and get them all home before the others.',
    instructions_es: 'Click en el dado para lanzar. Click en la ficha para moverla según los puntos obtenidos.',
    instructions_en: 'Click the die to roll. Click the piece to move it according to points rolled.',
    embed_url: 'https://www.crazygames.com/embed/ludo-online',
    thumb_url: '/thumbs/ludo-online.svg',
    min_players: 2, max_players: 4,
    category_slugs: ['dos-jugadores', 'multijugador', 'cuatro-jugadores'],
  },
];

async function run() {
  for (const g of games) {
    await sql`
      INSERT INTO games (
        slug, source, featured, title_es, title_en, tagline_es, tagline_en,
        description_es, description_en, instructions_es, instructions_en,
        embed_url, thumb_url, min_players, max_players, category_slugs,
        plays_count, rating_avg, published_at, updated_at
      ) VALUES (
        ${g.slug}, 'manual', ${(g as any).featured ?? false},
        ${g.title_es}, ${g.title_en}, ${g.tagline_es}, ${g.tagline_en},
        ${g.description_es}, ${g.description_en},
        ${g.instructions_es}, ${g.instructions_en},
        ${g.embed_url}, ${g.thumb_url},
        ${g.min_players}, ${g.max_players}, ${g.category_slugs},
        0, '0', NOW(), NOW()
      ) ON CONFLICT (slug) DO NOTHING
    `;
    console.log(`✓ ${g.slug}`);
  }
}
run().catch(console.error);
