import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL!);

const games = [
  // ─── .io games (verified embeddable, no X-Frame-Options) ────────────────
  {
    slug: 'krunker-io',
    source: 'manual', featured: false,
    title_es: 'Krunker.io', title_en: 'Krunker.io',
    tagline_es: 'Shooter FPS multijugador online en el navegador.',
    tagline_en: 'Online multiplayer FPS shooter in your browser.',
    description_es: 'Krunker.io es el shooter FPS multijugador más popular del navegador. Gráficos low-poly, mecánicas de movimiento avanzadas (slide, bunny-hop), decenas de mapas y modos de juego. Crea una sala privada con tus amigos o únete a partidas públicas.',
    description_en: 'Krunker.io is the most popular browser FPS. Low-poly graphics, advanced movement (slide, bunny-hop), dozens of maps and game modes. Create a private room with friends or join public matches.',
    instructions_es: 'WASD mover · Ratón apuntar · Click izq disparar · Shift agacharse · Espacio saltar',
    instructions_en: 'WASD move · Mouse aim · Left click shoot · Shift crouch · Space jump',
    embed_url: 'https://krunker.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 12,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'slither-io',
    source: 'manual', featured: false,
    title_es: 'Slither.io', title_en: 'Slither.io',
    tagline_es: 'La serpiente multijugador online más adictiva del navegador.',
    tagline_en: 'The most addictive online multiplayer snake game in your browser.',
    description_es: 'Controla una serpiente y come puntos de luz para crecer. Si otro jugador choca contra tu cuerpo, muere. Si tú chocas contra cualquier cuerpo, mueres. Sobrevive el máximo tiempo posible y sé la serpiente más grande del servidor.',
    description_en: 'Control a snake and eat light particles to grow. If another player hits your body, they die. If you hit any body, you die. Survive as long as possible and become the biggest snake on the server.',
    instructions_es: 'Mueve el ratón para dirigir la serpiente. Pulsa o mantén el botón para acelerar (pero pierdes masa).',
    instructions_en: 'Move the mouse to steer your snake. Click or hold to boost (but you lose mass).',
    embed_url: 'https://slither.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 500,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'diep-io',
    source: 'manual', featured: false,
    title_es: 'Diep.io', title_en: 'Diep.io',
    tagline_es: 'Tanques multijugador online con progresión y evolución.',
    tagline_en: 'Online multiplayer tanks with progression and evolution.',
    description_es: 'Controla un tanque y destruye formas geométricas para ganar XP. Sube de nivel y mejora tus estadísticas: velocidad, daño, penetración. Elige entre más de 50 clases de tanques. Modos equipo disponibles para jugar cooperativamente.',
    description_en: 'Control a tank and destroy geometric shapes to earn XP. Level up and improve stats: speed, damage, penetration. Choose from 50+ tank classes. Team modes available for cooperative play.',
    instructions_es: 'WASD o flechas mover · Ratón apuntar · Click izq disparar · U/K/O para subir stats',
    instructions_en: 'WASD or arrows move · Mouse aim · Left click shoot · U/K/O to upgrade stats',
    embed_url: 'https://diep.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 50,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'splix-io',
    source: 'manual', featured: false,
    title_es: 'Splix.io', title_en: 'Splix.io',
    tagline_es: 'Conquista el mayor territorio posible en este .io de estrategia.',
    tagline_en: 'Conquer as much territory as possible in this strategy .io game.',
    description_es: 'Mueve tu personaje para pintar el suelo de tu color y conquistar territorio. Mientras estás fuera de tu zona eres vulnerable — si alguien te corta el camino de vuelta, mueres. Estrategia, riesgo y reflejos en tiempo real.',
    description_en: 'Move your character to paint the ground your color and conquer territory. While outside your zone you are vulnerable — if someone cuts your path back, you die. Strategy, risk and real-time reflexes.',
    instructions_es: 'Flechas o WASD para mover. Expande tu territorio con cuidado.',
    instructions_en: 'Arrow keys or WASD to move. Expand your territory carefully.',
    embed_url: 'https://splix.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 100,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'paper-io-2',
    source: 'manual', featured: false,
    title_es: 'Paper.io 2', title_en: 'Paper.io 2',
    tagline_es: 'Pinta el mapa de tu color y domina el territorio.',
    tagline_en: 'Paint the map your color and dominate the territory.',
    description_es: 'Versión mejorada del clásico de conquista de territorio. Mueve tu cuadrado para pintar el suelo y capturar zonas. Elimina a otros jugadores cortando su línea. Efectos visuales espectaculares cuando el mapa se llena de colores.',
    description_en: 'Improved version of the classic territory conquest. Move your square to paint the ground and capture zones. Eliminate other players by cutting their line. Spectacular visual effects as the map fills with colors.',
    instructions_es: 'Desliza el dedo (móvil) o usa las flechas (PC) para mover tu personaje.',
    instructions_en: 'Swipe (mobile) or use arrow keys (PC) to move your character.',
    embed_url: 'https://paper-io.com',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 100,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'shell-shockers',
    source: 'manual', featured: false,
    title_es: 'Shell Shockers', title_en: 'Shell Shockers',
    tagline_es: 'Shooter FPS multijugador protagonizado por huevos armados.',
    tagline_en: 'Multiplayer FPS shooter starring armed eggs.',
    description_es: 'FPS multijugador único donde todos los personajes son huevos. Elige tu clase de huevo y tu arma, y elimina a los demás antes de que te frían a ti. Varios modos de juego, mapas variados y una estética caótica y divertida.',
    description_en: 'Unique multiplayer FPS where all characters are eggs. Choose your egg class and weapon, and eliminate others before they fry you. Several game modes, varied maps and a chaotic, fun aesthetic.',
    instructions_es: 'WASD mover · Ratón apuntar · Click izq disparar · E cambiar arma · Q lanzar granada',
    instructions_en: 'WASD move · Mouse aim · Left click shoot · E switch weapon · Q throw grenade',
    embed_url: 'https://shellshock.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 16,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'wormate-io',
    source: 'manual', featured: false,
    title_es: 'Wormate.io', title_en: 'Wormate.io',
    tagline_es: 'Gusano multijugador online que come dulces para crecer.',
    tagline_en: 'Online multiplayer worm that eats sweets to grow.',
    description_es: 'Gusano multijugador con un toque dulce: en vez de puntos de luz, recoges pasteles, donas y caramelos. Crece, usa habilidades especiales (escudo, magnet, velocidad) y elimina a otros gusanos. Más colorido y rápido que Slither.io.',
    description_en: 'Multiplayer worm with a sweet twist: instead of light particles, you collect cakes, donuts and candies. Grow, use special skills (shield, magnet, speed) and eliminate other worms. More colorful and faster than Slither.io.',
    instructions_es: 'Mueve el ratón para dirigir el gusano. Haz clic para acelerar.',
    instructions_en: 'Move the mouse to steer the worm. Click to boost.',
    embed_url: 'https://wormate.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 200,
    category_slugs: ['multijugador'],
  },
  {
    slug: 'surviv-io',
    source: 'manual', featured: false,
    title_es: 'Surviv.io', title_en: 'Surviv.io',
    tagline_es: 'Battle royale 2D multijugador online directo en el navegador.',
    tagline_en: '2D online multiplayer battle royale straight in your browser.',
    description_es: 'Battle royale 2D en vista cenital. Caes en una isla, buscas armas y objetos, la zona roja se encoge y el último en pie gana. Modos solo y dúo para jugar con un amigo. Partidas de 10-15 minutos perfectas para sesiones cortas.',
    description_en: '2D top-down battle royale. Drop on an island, find weapons and items, the red zone shrinks and last one standing wins. Solo and duo modes to play with a friend. 10-15 minute matches perfect for short sessions.',
    instructions_es: 'WASD mover · Ratón apuntar · Click izq disparar · F interactuar · R recargar',
    instructions_en: 'WASD move · Mouse aim · Left click shoot · F interact · R reload',
    embed_url: 'https://surviv.io',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 2, max_players: 80,
    category_slugs: ['multijugador'],
  },
  // ─── CrazyGames 2-player (verified 200 OK on embed URLs) ────────────────
  {
    slug: 'getaway-shootout',
    source: 'manual', featured: false,
    title_es: 'Getaway Shootout', title_en: 'Getaway Shootout',
    tagline_es: 'Carrera caótica para 2 jugadores: salta, dispara y escapa primero.',
    tagline_en: 'Chaotic race for 2 players: jump, shoot and escape first.',
    description_es: 'Getaway Shootout es un caótico juego de 2 jugadores en el mismo teclado. Compite contra tu amigo (o contra la IA) para ser el primero en llegar al punto de extracción. Recoge armas, úsalas contra tu rival y usa el terreno a tu favor. Movimiento saltarín y física impredecible garantizan risas.',
    description_en: 'Getaway Shootout is a chaotic 2-player game on the same keyboard. Race your friend (or AI) to be the first to reach the extraction point. Pick up weapons, use them on your rival and use the terrain to your advantage. Bouncy movement and unpredictable physics guarantee laughs.',
    instructions_es: 'Jugador 1: W saltar, E disparar/usar. Jugador 2: I saltar, O disparar/usar.',
    instructions_en: 'Player 1: W jump, E shoot/use. Player 2: I jump, O shoot/use.',
    embed_url: 'https://www.crazygames.com/embed/getaway-shootout',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'rooftop-snipers',
    source: 'manual', featured: false,
    title_es: 'Rooftop Snipers', title_en: 'Rooftop Snipers',
    tagline_es: 'Duelo de francotiradores en tejados para 2 jugadores.',
    tagline_en: '2-player rooftop sniper duel.',
    description_es: 'Dos personajes en un tejado, un rifle cada uno. El primero que tire al otro al vacío gana la ronda. Controles de 2 botones por jugador — simplísimo de aprender, muy divertido de dominar. Perfecto para sesiones rápidas con un amigo en el mismo ordenador.',
    description_en: 'Two characters on a rooftop, one rifle each. First to knock the other off wins the round. 2-button controls per player — extremely simple to learn, very fun to master. Perfect for quick sessions with a friend on the same computer.',
    instructions_es: 'Jugador 1: W saltar, E disparar. Jugador 2: I saltar, O disparar.',
    instructions_en: 'Player 1: W jump, E shoot. Player 2: I jump, O shoot.',
    embed_url: 'https://www.crazygames.com/embed/rooftop-snipers',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'basketball-stars',
    source: 'manual', featured: false,
    title_es: 'Basketball Stars', title_en: 'Basketball Stars',
    tagline_es: 'Baloncesto 1vs1 online multijugador en el navegador.',
    tagline_en: '1v1 online multiplayer basketball in your browser.',
    description_es: 'Juego de baloncesto 1 contra 1 con controles intuitivos. Compite online contra otros jugadores o desafía a un amigo. Haz fintas, bloquea tiros y encesta para ganar. Gráficos modernos y jugabilidad adictiva.',
    description_en: '1v1 basketball game with intuitive controls. Compete online against other players or challenge a friend. Make feints, block shots and score to win. Modern graphics and addictive gameplay.',
    instructions_es: 'Ratón o táctil para mover y lanzar. Sigue las indicaciones en pantalla.',
    instructions_en: 'Mouse or touch to move and shoot. Follow on-screen instructions.',
    embed_url: 'https://www.crazygames.com/embed/basketball-stars',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
  {
    slug: 'stickman-duelist-2',
    source: 'manual', featured: false,
    title_es: 'Stickman Supreme Duelist 2', title_en: 'Stickman Supreme Duelist 2',
    tagline_es: 'Combate de stickman para 2 jugadores con armas épicas.',
    tagline_en: '2-player stickman combat with epic weapons.',
    description_es: 'Juego de lucha para 2 jugadores en el mismo teclado. Controla a tu stickman y elimina al rival usando una variedad de armas: espadas, pistolas, hachas... Defiende, ataca y gana las rondas. Física divertida y acción rápida.',
    description_en: 'Fighting game for 2 players on the same keyboard. Control your stickman and eliminate the rival using various weapons: swords, guns, axes... Defend, attack and win the rounds. Fun physics and fast action.',
    instructions_es: 'Jugador 1: WASD mover, G atacar. Jugador 2: Flechas mover, L atacar.',
    instructions_en: 'Player 1: WASD move, G attack. Player 2: Arrows move, L attack.',
    embed_url: 'https://www.crazygames.com/embed/stickman-supreme-duelist-2',
    thumb_url: '/thumbs/placeholder.svg',
    min_players: 1, max_players: 2,
    category_slugs: ['dos-jugadores', 'multijugador'],
  },
];

async function run() {
  let added = 0;
  for (const g of games) {
    await sql`
      INSERT INTO games (
        slug, source, featured,
        title_es, title_en, tagline_es, tagline_en,
        description_es, description_en,
        instructions_es, instructions_en,
        embed_url, thumb_url,
        min_players, max_players, category_slugs,
        plays_count, rating_avg, published_at, updated_at
      ) VALUES (
        ${g.slug}, ${g.source}, ${g.featured},
        ${g.title_es}, ${g.title_en}, ${g.tagline_es}, ${g.tagline_en},
        ${g.description_es}, ${g.description_en},
        ${g.instructions_es}, ${g.instructions_en},
        ${g.embed_url}, ${g.thumb_url},
        ${g.min_players}, ${g.max_players}, ${g.category_slugs},
        0, '0', NOW(), NOW()
      ) ON CONFLICT (slug) DO NOTHING
    `;
    console.log(`✓ ${g.slug}`);
    added++;
  }
  console.log(`\nAdded ${added} games. Go to /admin/games to verify embed URLs.`);
}
run().catch(console.error);
